[package]
name = "passport-input-gen"
version = "0.1.0"
edition = "2021"
description = "Passport input generator"

[dependencies]
rsa = { version = "0.9.8", features = ["sha2"] }
sha2 = { version = "0.10", features = ["compress"] }

[[bin]]
name = "passport-input-generator"
path = "src/main.rs"
