[package]
name = "passport_input_gen"
version = "0.1.0"
edition = "2021"

[dependencies]
rsa = { version = "0.9.8", features = ["sha2"] }
sha2 = { version = "0.10", features = ["compress"] }

[[bin]]
name = "generate"
path = "src/main.rs"
